### PR TITLE
Fix PKGBUILD var error

### PR DESCRIPTION
**Pull request by NextAlone**

### CODE REVIEW

**Comment by simon04** [comment]
How is this incorrect? It is a 1:1 copy from https://wiki.archlinux.org/title/Node.js_package_guidelines

**Comment by NextAlone** [comment]
```
npm2archinstall wcwidth

Error: Registry returned ReferenceError: pkgdir is not defined for GET on https://registry.npmjs.org/wcwidth/latest
    at /usr/lib/node_modules/@simon04/npm2arch/lib/npm2PKGBUILD.js:67:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
What shows in my shell is as above

I think that the `${var}` patten diff between javascript and shell. `${pkgdir}` can be parsed in javascript to find variable `pkgdir` in javascript, not string print to PKGBUILD file. Or it written as `$\{pkgdir\}` patten.

Hope that what i said is clear.

**Comment by NextAlone** [comment]
AndGitHub actions test indicates the error too. Link and screenshot are as follows.
https://github.com/simon04/npm2arch/runs/4200518022?check_suite_focus=true
image

**Comment by simon04** [comment]
Alrigfht, I'm convinced. `${pkgdir}` is erroneously being interpreted by JavaScript. Thank you for this patch!

**Comment by NextAlone** [comment]
Yeah, thanks for your work too. And would u please bump version and update which is on aur.

**Comment by simon04** [comment]
Released as v2.2.0 on https://github.com/simon04/npm2arch/releases/tag/v2.2.0 and https://aur.archlinux.org/packages/nodejs-npm2arch/

**Comment by NextAlone** [comment]
Ok, just seen that, thanks again.

**Pull request merged**
